### ISSUE TITLE
Import Error!

### ISSUE THREAD

**Issue by Juzz4vijay** [YueLiao/PPDM#2]
Import Error:

Thanks in advance

Code:

%cd /content/PPDM/src
!python /content/PPDM/src/test_hoi.py --exp_id hoidet_hico_dla --gpus 0 --dataset hico --image_dir images/test2015 --test_with_eval

ERROR:

/content/PPDM/src
Traceback (most recent call last):
  File "/content/PPDM/src/test_hoi.py", line 16, in <module>
    from detectors.detector_factory import detector_factory
  File "/content/PPDM/src/lib/detectors/detector_factory.py", line 5, in <module>
    from .hoidet import HoidetDetector
  File "/content/PPDM/src/lib/detectors/hoidet.py", line 12, in <module>
    from .base_detector import BaseDetector
  File "/content/PPDM/src/lib/detectors/base_detector.py", line 11, in <module>
    from models.model import create_model, load_model
  File "/content/PPDM/src/lib/models/model.py", line 8, in <module>
    from .networks.pose_dla_dcn import get_pose_net as get_dla_dcn
  File "/content/PPDM/src/lib/models/networks/pose_dla_dcn.py", line 16, in <module>
    from .DCNv2.dcn_v2 import DCN
  File "/content/PPDM/src/lib/models/networks/DCNv2/dcn_v2.py", line 11, in <module>
    from .dcn_v2_func import DCNv2Function
  File "/content/PPDM/src/lib/models/networks/DCNv2/dcn_v2_func.py", line 9, in <module>
    from ._ext import dcn_v2 as _backend
  File "/content/PPDM/src/lib/models/networks/DCNv2/_ext/dcn_v2/__init__.py", line 3, in <module>
    from ._dcn_v2 import lib as _lib, ffi as _ffi
ImportError: /content/PPDM/src/lib/models/networks/DCNv2/_ext/dcn_v2/_dcn_v2.so: undefined symbol: __cudaPopCallConfiguration

**Comment by YueLiao** [comment]
This is because Pytorch 0.4.1 does not support cuda>=10.0. So, the solution is to install another version of cuda 9.0.

**Comment by Juzz4vijay** [comment]
Can you guide me, how to prepare HOI-A kind of own dataset.?

I've gone through reseearch paper.. 

But, i need some sample dataset.. it'll give me a clear picture to preparing our own dataset.

**Comment by Juzz4vijay** [comment]
Can you guide me, how to prepare HOI-A kind of own dataset.?

I've gone through reseearch paper.. 

But, i need some sample dataset.. it'll give me a clear picture to preparing our own dataset.

**Comment by YueLiao** [comment]
The 'HOI-A' dataset is an extension and refinement of our proposed 'HOI-W' dataset for the ICCV 2019 PIC workshop HOI detection challenge. The format of 'HOI-A' is the same as 'HOI-W'. You can take the '[HOI-W](http://picdataset.com/challenge/dataset/download/)' dataset as a reference. Moreover, we have provided the 'HICO-Det'  annotations, which have been transformed into 'HOI-A' format. You can perform experiments on 'HICO-Det' directly.

**Comment by Juzz4vijay** [comment]
Thanks for your valuable response.
